// frontend/src/app/components/deliberation-view/deliberation-view.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Deliberation } from '../../models';
import { PerspectiveCardComponent } from '../perspective-card/perspective-card.component';
import { SynthesisPanelComponent } from '../synthesis-panel/synthesis-panel.component';

@Component({
  selector: 'app-deliberation-view',
  standalone: true,
  imports: [CommonModule, PerspectiveCardComponent, SynthesisPanelComponent],
  templateUrl: './deliberation-view.component.html',
  styleUrls: ['./deliberation-view.component.scss'],
})
export class DeliberationViewComponent {
  @Input() deliberation!: Deliberation;
  @Output() saveClicked = new EventEmitter<void>();
  @Output() newQuestion = new EventEmitter<void>();

  expandedPerspective: string | null = null;
  activeTab: 'synthesis' | 'perspectives' = 'synthesis';

  get formattedTimestamp(): string {
    return new Date(this.deliberation.timestamp).toLocaleString();
  }

  togglePerspective(memberId: string): void {
    this.expandedPerspective =
      this.expandedPerspective === memberId ? null : memberId;
  }

  onSave(): void {
    this.saveClicked.emit();
  }

  onNewQuestion(): void {
    this.newQuestion.emit();
  }
}

<div class="deliberation-view">
  <!-- Question Header -->
  <div class="card question-header">
    <div class="question-content">
      <div class="question-text">
        <p class="label">Question</p>
        <h1>{{ deliberation.question }}</h1>
        <p class="meta">
          {{ deliberation.perspectives.length }} perspectives ·
          {{ deliberation.disagreements.length }} disagreements ·
          {{ formattedTimestamp }}
        </p>
      </div>
      <div class="question-actions">
        <button class="btn btn-secondary" (click)="onSave()">
          <span>🔐</span> Save
        </button>
        <button class="btn btn-primary" (click)="onNewQuestion()">
          New Question
        </button>
      </div>
    </div>
  </div>

  <!-- Tab Navigation -->
  <div class="tabs">
    <button
      class="tab"
      [class.active]="activeTab === 'synthesis'"
      (click)="activeTab = 'synthesis'"
    >
      Synthesis
    </button>
    <button
      class="tab"
      [class.active]="activeTab === 'perspectives'"
      (click)="activeTab = 'perspectives'"
    >
      Perspectives ({{ deliberation.perspectives.length }})
    </button>
  </div>

  <!-- Tab Content -->
  <div class="tab-content">
    <app-synthesis-panel
      *ngIf="activeTab === 'synthesis'"
      [synthesis]="deliberation.synthesis"
      [disagreements]="deliberation.disagreements"
      [minorityReports]="deliberation.minority_reports"
    ></app-synthesis-panel>

    <div class="perspectives-list" *ngIf="activeTab === 'perspectives'">
      <app-perspective-card
        *ngFor="let perspective of deliberation.perspectives"
        [perspective]="perspective"
        [isExpanded]="expandedPerspective === perspective.member_id"
        (toggle)="togglePerspective(perspective.member_id)"
      ></app-perspective-card>
    </div>
  </div>
</div>

// frontend/src/components/DeliberationView.tsx
/**
 * Main view for displaying a completed deliberation.
 */

import { useState } from 'react';
import type { Deliberation } from '../types';
import { PerspectiveCard } from './PerspectiveCard';
import { SynthesisPanel } from './SynthesisPanel';

interface DeliberationViewProps {
  deliberation: Deliberation;
  onSave: () => void;
  onNewQuestion: () => void;
}

export function DeliberationView({
  deliberation,
  onSave,
  onNewQuestion,
}: DeliberationViewProps) {
  const [expandedPerspective, setExpandedPerspective] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'synthesis' | 'perspectives'>('synthesis');

  return (
    <div className="space-y-6">
      {/* Question Header */}
      <div className="bg-council-surface rounded-lg p-6 border border-council-border">
        <div className="flex items-start justify-between gap-4">
          <div>
            <p className="text-xs text-gray-500 mb-1">Question</p>
            <h1 className="text-xl text-white font-medium">{deliberation.question}</h1>
            <p className="text-xs text-gray-500 mt-2">
              {deliberation.perspectives.length} perspectives ·{' '}
              {deliberation.disagreements.length} disagreements ·{' '}
              {new Date(deliberation.timestamp).toLocaleString()}
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={onSave}
              className="px-3 py-1.5 text-sm bg-council-border hover:bg-gray-600 rounded transition-colors flex items-center gap-1"
            >
              <span>🔐</span> Save
            </button>
            <button
              onClick={onNewQuestion}
              className="px-3 py-1.5 text-sm bg-council-accent hover:bg-blue-600 text-white rounded transition-colors"
            >
              New Question
            </button>
          </div>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="flex border-b border-council-border">
        <button
          onClick={() => setActiveTab('synthesis')}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            activeTab === 'synthesis'
              ? 'text-council-accent border-b-2 border-council-accent'
              : 'text-gray-400 hover:text-white'
          }`}
        >
          Synthesis
        </button>
        <button
          onClick={() => setActiveTab('perspectives')}
          className={`px-4 py-2 text-sm font-medium transition-colors ${
            activeTab === 'perspectives'
              ? 'text-council-accent border-b-2 border-council-accent'
              : 'text-gray-400 hover:text-white'
          }`}
        >
          Perspectives ({deliberation.perspectives.length})
        </button>
      </div>

      {/* Tab Content */}
      {activeTab === 'synthesis' ? (
        <SynthesisPanel
          synthesis={deliberation.synthesis}
          disagreements={deliberation.disagreements}
          minorityReports={deliberation.minority_reports}
        />
      ) : (
        <div className="space-y-3">
          {deliberation.perspectives.map((perspective) => (
            <PerspectiveCard
              key={perspective.member_id}
              perspective={perspective}
              isExpanded={expandedPerspective === perspective.member_id}
              onToggle={() =>
                setExpandedPerspective(
                  expandedPerspective === perspective.member_id
                    ? null
                    : perspective.member_id
                )
              }
            />
          ))}
        </div>
      )}
    </div>
  );
}
