// frontend/src/components/SynthesisPanel.tsx
/**
 * Panel displaying the chairman's synthesis.
 */

import type { Synthesis, Disagreement, MinorityReport } from '../types';

interface SynthesisPanelProps {
  synthesis: Synthesis;
  disagreements: Disagreement[];
  minorityReports: MinorityReport[];
}

function ConfidenceMeter({ value, label }: { value: number; label: string }) {
  const percentage = Math.round(value * 100);
  const color =
    value >= 0.7 ? 'bg-green-500' : value >= 0.4 ? 'bg-yellow-500' : 'bg-red-500';

  return (
    <div className="flex items-center gap-2">
      <span className="text-xs text-gray-400 w-24">{label}</span>
      <div className="flex-1 h-2 bg-council-border rounded-full overflow-hidden">
        <div
          className={`h-full ${color} transition-all`}
          style={{ width: `${percentage}%` }}
        />
      </div>
      <span className="text-xs text-gray-300 w-12 text-right">{percentage}%</span>
    </div>
  );
}

function SeverityBadge({ severity }: { severity?: string }) {
  const colors: Record<string, string> = {
    minor: 'bg-blue-900 text-blue-300',
    moderate: 'bg-yellow-900 text-yellow-300',
    fundamental: 'bg-red-900 text-red-300',
  };

  const color = colors[severity || 'moderate'] || colors.moderate;

  return (
    <span className={`px-2 py-0.5 text-xs rounded ${color}`}>
      {severity || 'moderate'}
    </span>
  );
}

export function SynthesisPanel({
  synthesis,
  disagreements,
  minorityReports,
}: SynthesisPanelProps) {
  return (
    <div className="space-y-6">
      {/* Main Synthesis */}
      <div className="bg-council-surface rounded-lg p-6 border border-council-border">
        <div className="flex items-center gap-2 mb-4">
          <span className="text-2xl">⚖️</span>
          <h2 className="text-xl font-semibold text-white">Council Synthesis</h2>
        </div>

        <div className="prose-council text-gray-300 whitespace-pre-wrap">
          {synthesis.content}
        </div>

        {/* Confidence Score */}
        {synthesis.confidence && (
          <div className="mt-6 pt-4 border-t border-council-border">
            <h3 className="text-sm font-semibold text-gray-400 mb-3">
              Confidence Assessment
            </h3>
            <div className="space-y-2">
              <ConfidenceMeter
                value={synthesis.confidence.overall}
                label="Overall"
              />
              <ConfidenceMeter
                value={synthesis.confidence.consensus_strength}
                label="Consensus"
              />
              <ConfidenceMeter
                value={synthesis.confidence.dissent_strength}
                label="Dissent"
              />
            </div>
            <p className="mt-2 text-xs text-gray-500 italic">
              {synthesis.confidence.reasoning}
            </p>
          </div>
        )}
      </div>

      {/* Consensus Points */}
      {synthesis.consensus_points.length > 0 && (
        <div className="bg-council-surface rounded-lg p-4 border border-green-900">
          <h3 className="text-sm font-semibold text-green-400 mb-2 flex items-center gap-2">
            <span>✓</span> Points of Agreement
          </h3>
          <ul className="space-y-1">
            {synthesis.consensus_points.map((point, i) => (
              <li key={i} className="text-sm text-gray-300 flex items-start gap-2">
                <span className="text-green-500">•</span>
                {point}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Divisions */}
      {synthesis.divisions.length > 0 && (
        <div className="bg-council-surface rounded-lg p-4 border border-yellow-900">
          <h3 className="text-sm font-semibold text-yellow-400 mb-2 flex items-center gap-2">
            <span>⚡</span> Areas of Division
          </h3>
          <ul className="space-y-1">
            {synthesis.divisions.map((division, i) => (
              <li key={i} className="text-sm text-gray-300 flex items-start gap-2">
                <span className="text-yellow-500">•</span>
                {division}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Unique Insights */}
      {synthesis.unique_insights.length > 0 && (
        <div className="bg-council-surface rounded-lg p-4 border border-purple-900">
          <h3 className="text-sm font-semibold text-purple-400 mb-2 flex items-center gap-2">
            <span>💡</span> Unique Insights
          </h3>
          <ul className="space-y-1">
            {synthesis.unique_insights.map((insight, i) => (
              <li key={i} className="text-sm text-gray-300 flex items-start gap-2">
                <span className="text-purple-500">•</span>
                {insight}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Disagreements */}
      {disagreements.length > 0 && (
        <div className="bg-council-surface rounded-lg p-4 border border-council-border">
          <h3 className="text-sm font-semibold text-gray-400 mb-3 flex items-center gap-2">
            <span>🔍</span> Detailed Disagreements
          </h3>
          <div className="space-y-4">
            {disagreements.map((d, i) => (
              <div key={i} className="border-l-2 border-council-border pl-3">
                <div className="flex items-center gap-2 mb-1">
                  <h4 className="font-medium text-white">{d.topic}</h4>
                  <SeverityBadge severity={d.severity} />
                </div>
                <p className="text-sm text-gray-400 mb-2">{d.description}</p>
                <div className="space-y-1">
                  {Object.entries(d.positions).map(([member, position]) => (
                    <div key={member} className="text-sm">
                      <span className="text-council-accent capitalize">{member}:</span>{' '}
                      <span className="text-gray-300">{position}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Minority Reports */}
      {minorityReports.length > 0 && (
        <div className="bg-council-surface rounded-lg p-4 border border-red-900">
          <h3 className="text-sm font-semibold text-red-400 mb-3 flex items-center gap-2">
            <span>📋</span> Minority Reports
          </h3>
          <div className="space-y-4">
            {minorityReports.map((report, i) => (
              <div key={i} className="border-l-2 border-red-800 pl-3">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-lg font-serif text-red-400 capitalize">
                    {report.member_id}
                  </span>
                </div>
                <p className="text-sm text-white font-medium">{report.position}</p>
                <p className="text-sm text-gray-400 mt-1">{report.rationale}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// frontend/src/app/components/synthesis-panel/synthesis-panel.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Synthesis, Disagreement, MinorityReport } from '../../models';

@Component({
  selector: 'app-synthesis-panel',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './synthesis-panel.component.html',
  styleUrls: ['./synthesis-panel.component.scss'],
})
export class SynthesisPanelComponent {
  @Input() synthesis!: Synthesis;
  @Input() disagreements: Disagreement[] = [];
  @Input() minorityReports: MinorityReport[] = [];

  getConfidencePercentage(value: number): number {
    return Math.round(value * 100);
  }

  getConfidenceColor(value: number): string {
    if (value >= 0.7) return 'bg-green';
    if (value >= 0.4) return 'bg-yellow';
    return 'bg-red';
  }

  getSeverityClass(severity?: string): string {
    switch (severity) {
      case 'minor':
        return 'severity-minor';
      case 'fundamental':
        return 'severity-fundamental';
      default:
        return 'severity-moderate';
    }
  }

  getPositionEntries(positions: Record<string, string>): Array<{ key: string; value: string }> {
    return Object.entries(positions).map(([key, value]) => ({ key, value }));
  }
}

<div class="synthesis-container">
  <!-- Main Synthesis -->
  <div class="card synthesis-main">
    <div class="section-header">
      <span class="header-icon">⚖️</span>
      <h2>Council Synthesis</h2>
    </div>

    <div class="synthesis-content">{{ synthesis().content }}</div>

    <!-- Confidence Score -->
    @if (synthesis().confidence; as confidence) {
      <div class="confidence-section">
        <h3>Confidence Assessment</h3>
        <div class="confidence-meters">
          <div class="meter">
            <span class="meter-label">Overall</span>
            <div class="meter-track">
              <div
                class="meter-fill"
                [class]="getConfidenceColor(confidence.overall)"
                [style.width.%]="getConfidencePercentage(confidence.overall)"
              ></div>
            </div>
            <span class="meter-value">{{ getConfidencePercentage(confidence.overall) }}%</span>
          </div>
          <div class="meter">
            <span class="meter-label">Consensus</span>
            <div class="meter-track">
              <div
                class="meter-fill"
                [class]="getConfidenceColor(confidence.consensus_strength)"
                [style.width.%]="getConfidencePercentage(confidence.consensus_strength)"
              ></div>
            </div>
            <span class="meter-value">{{ getConfidencePercentage(confidence.consensus_strength) }}%</span>
          </div>
          <div class="meter">
            <span class="meter-label">Dissent</span>
            <div class="meter-track">
              <div
                class="meter-fill"
                [class]="getConfidenceColor(confidence.dissent_strength)"
                [style.width.%]="getConfidencePercentage(confidence.dissent_strength)"
              ></div>
            </div>
            <span class="meter-value">{{ getConfidencePercentage(confidence.dissent_strength) }}%</span>
          </div>
        </div>
        <p class="confidence-reasoning">{{ confidence.reasoning }}</p>
      </div>
    }
  </div>

  <!-- Consensus Points -->
  @if (synthesis().consensus_points.length > 0) {
    <div class="card consensus-card">
      <h3><span>✓</span> Points of Agreement</h3>
      <ul>
        @for (point of synthesis().consensus_points; track point) {
          <li>
            <span class="bullet green">•</span>
            {{ point }}
          </li>
        }
      </ul>
    </div>
  }

  <!-- Divisions -->
  @if (synthesis().divisions.length > 0) {
    <div class="card divisions-card">
      <h3><span>⚡</span> Areas of Division</h3>
      <ul>
        @for (division of synthesis().divisions; track division) {
          <li>
            <span class="bullet yellow">•</span>
            {{ division }}
          </li>
        }
      </ul>
    </div>
  }

  <!-- Unique Insights -->
  @if (synthesis().unique_insights.length > 0) {
    <div class="card insights-card">
      <h3><span>💡</span> Unique Insights</h3>
      <ul>
        @for (insight of synthesis().unique_insights; track insight) {
          <li>
            <span class="bullet purple">•</span>
            {{ insight }}
          </li>
        }
      </ul>
    </div>
  }

  <!-- Disagreements -->
  @if (disagreements().length > 0) {
    <div class="card disagreements-card">
      <h3><span>🔍</span> Detailed Disagreements</h3>
      <div class="disagreement-list">
        @for (d of disagreements(); track d.topic) {
          <div class="disagreement-item">
            <div class="disagreement-header">
              <h4>{{ d.topic }}</h4>
              <span class="severity-badge" [class]="getSeverityClass(d.severity)">
                {{ d.severity || 'moderate' }}
              </span>
            </div>
            <p class="disagreement-desc">{{ d.description }}</p>
            <div class="positions">
              @for (pos of getPositionEntries(d.positions); track pos.key) {
                <div class="position">
                  <span class="position-member">{{ pos.key }}:</span>
                  <span class="position-text">{{ pos.value }}</span>
                </div>
              }
            </div>
          </div>
        }
      </div>
    </div>
  }

  <!-- Minority Reports -->
  @if (minorityReports().length > 0) {
    <div class="card minority-card">
      <h3><span>📋</span> Minority Reports</h3>
      <div class="minority-list">
        @for (report of minorityReports(); track report.member_id) {
          <div class="minority-item">
            <div class="minority-header">
              <span class="minority-member">{{ report.member_id }}</span>
            </div>
            <p class="minority-position">{{ report.position }}</p>
            <p class="minority-rationale">{{ report.rationale }}</p>
          </div>
        }
      </div>
    </div>
  }
</div>
